(library
 (name tiger)
 (modules :standard)
 (libraries menhirLib))

(rule
 (targets parser.ml parser.mli)
 (deps parse-spec.mly)
 (action
  (run menhir --explain --base parser %{deps})))

(rule
 (targets tigerLexer.ml)
 (deps tigerLexer.mll parser.mli)
 (action
  (run ocamllex -o %{targets} tigerLexer.mll)))
